[package]
name = "pss"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
skim = "0.10.4"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
home = "0.5"
